---
- name: Check and reboot servers with pending reboots
  hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Check for pending reboot
      shell: test -f /var/run/reboot-required
      register: reboot_needed
      ignore_errors: yes

    - name: Set reboot fact
      set_fact:
        needs_reboot: "{{ reboot_needed.rc == 0 }}"

    - name: Reboot if needed
      block:
        - name: Reboot the server
          shell: shutdown -r now "Reboot initiated by Ansible"
          async: 1
          poll: 0
          when: needs_reboot

        - name: Wait for server to go down
          pause:
            seconds: 20
          when: needs_reboot

        - name: Wait for server to come back up
          wait_for:
            host: "{{ inventory_hostname }}"
            port: 22
            state: started
            delay: 60
            timeout: 300
          when: needs_reboot
      when: needs_reboot