---
- name: Check for pending reboot on Ubuntu servers
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Set reboot status fact
      set_fact:
        reboot_required: "{{ reboot_required_file.stat.exists }}"

- name: Summarize reboot status
  hosts: localhost
  gather_facts: no
  vars:
    reboot_required_hosts: >-
      {{
        hostvars
        | dict2items
        | selectattr('value.reboot_required', 'defined')
        | selectattr('value.reboot_required', 'equalto', true)
        | map(attribute='key')
        | list
      }}
    reboot_not_required_hosts: >-
      {{
        hostvars
        | dict2items
        | selectattr('value.reboot_required', 'defined')
        | rejectattr('value.reboot_required', 'equalto', true)
        | map(attribute='key')
        | list
      }}
  tasks:
    - name: Show hosts that need reboot
      debug:
        msg: >-
          ⚠️  Reboot Required: {{
            reboot_required_hosts | join(', ') if reboot_required_hosts else 'none'
          }}

    - name: Show hosts that do NOT need reboot
      debug:
        msg: >-
          ✅ No Reboot Required: {{
            reboot_not_required_hosts | join(', ') if reboot_not_required_hosts else 'none'
          }}
