---
- name: Check for pending reboot on Ubuntu servers
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Set reboot status fact
      set_fact:
        reboot_required: "{{ reboot_required_file.stat.exists }}"

    - name: Print reboot summary
      run_once: true
      delegate_to: localhost
      vars:
        reboot_hosts: "{{ play_hosts | select('in', groups['all']) | list }}"
        reboot_required_hosts: "{{ reboot_hosts | select('match', '.*') | select('equalto', true, attribute='hostvars[.].reboot_required') | list }}"
        reboot_not_required_hosts: "{{ reboot_hosts | reject('equalto', true, attribute='hostvars[.].reboot_required') | list }}"
      block:
        - name: Show hosts that need reboot
          debug:
            msg: >-
              ⚠️  Reboot Required: {{
                reboot_required_hosts | default([]) | join(', ') if reboot_required_hosts else 'none'
              }}

        - name: Show hosts that do NOT need reboot
          debug:
            msg: >-
              ✅ No Reboot Required: {{
                reboot_not_required_hosts | default([]) | join(', ') if reboot_not_required_hosts else 'none'
              }}
