---
- name: Check pending reboot on Ubuntu hosts
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Check if /var/run/reboot-required exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag

    - name: Set reboot_pending fact
      ansible.builtin.set_fact:
        reboot_pending: "{{ reboot_flag.stat.exists | default(false) }}"

    - name: Show reboot status
      ansible.builtin.debug:
        msg: >
          Host {{ inventory_hostname }} reboot pending: {{ reboot_pending }}