---
- name: Update all system packages except newrelic-infra (Ubuntu only)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if newrelic-infra is installed
      ansible.builtin.shell: |
        dpkg-query -W -f='${Status}' newrelic-infra 2>/dev/null | grep -q "install ok installed"
      register: newrelic_installed
      ignore_errors: yes
      changed_when: false

    - name: Hold newrelic-infra (if installed)
      ansible.builtin.command: apt-mark hold newrelic-infra
      when: newrelic_installed.rc == 0
      become: yes
      register: hold_result
      changed_when: "'held back' in hold_result.stdout or hold_result.rc == 0"
      ignore_errors: yes

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages except newrelic-infra
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: yes

    - name: Unhold newrelic-infra (if it was held)
      ansible.builtin.command: apt-mark unhold newrelic-infra
      when: newrelic_installed.rc == 0
      become: yes
      register: unhold_result
      changed_when: "'unhold' in unhold_result.stdout or unhold_result.rc == 0"
      ignore_errors: yes
